name: Weather CI

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Prepare Maps API Keys
      env:
        MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
      run: echo maps_api_key=\"MAPS_API_KEY\" > ./local.properties

    - name: Prepare Weather API Keys
      env:
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      run: echo weather_api_key=\"WEATHER_API_KEY\" > ./local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Tests & Compile Reports
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew build jacocoTestReport assembleAndroidTest connectedCheck

    - name: Upload Test Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: Coverage Report
        path: app/build/outputs/androidTest-results/connected

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
